[pytest]    #第一行固定为pytest，声明此配置文件为pytest的配置文件

# -s表示输出print打印信息，-v表示输出详细信息，--html表示生成测试报告，报告路径为./report/report.html
addopts = -s -v --html=./report/report.html 

#测试用例的路径，pytest会自动搜索该路径下的所有测试用例文件
testpaths = ./script

#测试用例文件的匹配规则，pytest会自动匹配该规则下的测试用例文件
python_files = test*.py

#测试用例类的匹配规则，pytest会自动匹配该规则下的测试用例类
python_classes = Test*

#测试用例函数的匹配规则，pytest会自动匹配该规则下的测试用例函数
python_functions = test*